=== ABDO-DZ-39/xsd/Student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="FirstName" type="xs:string"/>
                            <xs:element name="FamilyName" type="xs:string"/>
                            <xs:element name="Age">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="17"/>
                                        <xs:maxInclusive value="70"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Address" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Number">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="0"/>
                                                    <xs:maxInclusive value="999"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="City">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="100"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="PostalCode">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{5}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Level">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="1L"/>
                                        <xs:enumeration value="2L"/>
                                        <xs:enumeration value="3L"/>
                                        <xs:enumeration value="1M"/>
                                        <xs:enumeration value="2M"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Speciality">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="ComputerScience"/>
                                        <xs:enumeration value="Physics"/>
                                        <xs:enumeration value="Chemistry"/>
                                        <xs:enumeration value="Mathematics"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Average">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0.00"/>
                                        <xs:maxInclusive value="20.00"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="RegistrationNumber" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="\d{8}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ABDO-DZ-39/xsd/Student (2).xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="student.xsd">

    <Student RegistrationNumber="222555">
        <FirstName>abd elmotaleb</FirstName>
        <FamilyName>alalei</FamilyName>
        <Age>21</Age>
        <Address>
            <Number>15</Number>
            <City>El Oued</City>
            <PostalCode>99051</PostalCode>
        </Address>
        <Level>3L</Level>
        <Speciality>ComputerScience</Speciality>
        <Average>12.55</Average>
    </Student>

    <Student RegistrationNumber="888791">
        <FirstName>ahmed</FirstName>
        <FamilyName>libia</FamilyName>
        <Age>20</Age>
        <Level>2L</Level>
        <Speciality>Mathematics</Speciality>
        <Average>17.80</Average>
    </Student>

</Students>
